[package]
name = "ire"
description = "I2P router implementation in Rust"
version = "0.0.1"
license = "MIT"
authors = ["Jack Grigg <str4d@i2pmail.org>"]
homepage = "https://github.com/str4d/ire"
repository = "https://github.com/str4d/ire"
readme = "README.md"
categories = ["cryptography"]
keywords = ["i2p", "net", "network", "privacy", "security"]

[dependencies]
aesti = "0.3"
arrayref = "0.3"
bytes = "0.4"
clap = "2.31"
cookie-factory = { git = "https://github.com/Geal/cookie-factory.git" }
ed25519-dalek = "0.6"
env_logger = "0.5"
flate2 = "1.0"
futures = "0.1"
itertools = "0.7"
lazy_static = "1.0"
log = "0.4"
nom = "3.2"
num = "0.1"
rand = "0.4"
sha2 = "0.7"
tokio-io = "0.1"
tokio-core = "0.1"

[dev-dependencies]
pretty_assertions = "0.5"
